# Generated by Django 5.2.5 on 2025-11-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_usuario_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamacao",
            name="status",
            field=models.CharField(
                choices=[("ABERTA", "Aberta"), ("ENCERRADA", "Encerrada")],
                default="ABERTA",
                max_length=20,
            ),
        ),
    ]
