services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - .env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:14-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - psql